export const issueDetailsCardStyle = 'bg-white p-4 mt-4 w-full rounded-md'
export const issueDetailsCardTitleStyle = 'text-base font-medium'
export const issueDetailsCardContentStyle = 'text-sm text-black'
export const issueDetailsCardPlaceholderStyle = 'text-sm text-gray-400'
export const issueDetailsCardSubtitleStyle = 'text-xs text-gray-600'
